name: Bundle app

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  push:
    branches: [main]
    tags: [v*]
  pull_request:
  workflow_dispatch:

jobs:
  bundle:
    name: ${{ matrix.platform }}
    runs-on: ${{ matrix.platform }}
    strategy:
      fail-fast: false
      matrix:
        platform: [macos-latest, windows-latest]

    steps:
      - uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          version: "0.5.11"
          enable-cache: true

      - name: Install the project
        run: uv sync --all-extras --dev

      - name: Bundle
        shell: bash
        run: |
          uv run pyinstaller app/mmgui.spec --clean --noconfirm
          ls -la dist/mmgui

      - name: Create DMG
        if: runner.os == 'macos'
        run: |
          ls -la dist/pymmgui.app/Contents/Resources
          mkdir dist/dmg
          ln -s /Applications dist/dmg
          # Use cp -P to preserve symlinks
          rsync -a --copy-links dist/pymmgui.app dist/dmg/
          ls -la dist/dmg/pymmgui.app/Contents/Resources
          hdiutil create -volname pymmgui -srcfolder dist/dmg -format UDZO dist/pymmgui.dmg
          rm -rf dist/dmg

      - name: Upload bundle
        uses: actions/upload-artifact@v4
        with:
          name: ${{ runner.os == 'macos' && 'pymmgui.dmg' || runner.os == 'windows' && 'pymmgui.exe' }}
          path: ${{ runner.os == 'macos' && 'dist/pymmgui.dmg' || runner.os == 'windows' && 'dist/mmgui/pymmgui.exe' }}
