name: Bundle app

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  push:
    branches: [main]
    tags: [v*]
  pull_request:
  workflow_dispatch:

jobs:
  bundle:
    name: ${{ matrix.platform }}
    runs-on: ${{ matrix.platform }}
    strategy:
      fail-fast: false
      matrix:
        platform: [macos-latest, windows-latest]

    steps:
      - uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          version: "0.5.11"
          enable-cache: true

      - name: Install the project
        run: uv sync --all-extras --dev

      - name: Bundle
        shell: bash
        run: |
          uv run pyinstaller app/mmgui.spec --clean --noconfirm
          ls -la dist/mmgui

      # - name: Create DMG
      #   if: runner.os == 'macos'
      #   run: |
      #     zip -r dist/pymmgui.zip dist/pymmgui.app

      - name: Upload bundle
        uses: eXhumer/upload-artifact@0b7d5f5684d3f642f978d2faad9ade64f5b4dd57
        with:
          name: pymmgui
          path: ${{ runner.os == 'macos' && 'dist/pymmgui.app' || runner.os == 'windows' && 'dist/mmgui/pymmgui.exe' }}
          follow-symlinks: false